# --- ВВОД -----------------------------------------------------------
input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options=grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = yes
    }
}

# Пример новой настройки жестов (если нужно)
# gesture = 3, horizontal, workspace
# gesture = 3, down, close

# Пример per-device config
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

