# --- ПРАВИЛА ОКОН ---------------------------------------------------
# See https://wiki.hyprland.org/Configuring/Window-Rules/

#windowrule = suppress_event maximize, class:.*
#windowrule = float, class:^(qalculate-gtk)$

