# Шрифт
font_family JetBrainsMono Nerd Font Mono

# Размер шрафта
font_size 14.0

# Прозрачность терминала
background_opacity 1

# Отступ по краям
window_padding_width 5

# Цвет фона и текста
background #282a36
foreground #c0caf5

# Цвет выделенного текста
selection_foreground #ffffff
selection_background #6ca1f3

# Оболочка по умолчанию
shell /bin/zsh

# Шлейф за курсором
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
