# Новый синтаксис hyprpaper для Hyprland 0.56+
# Путь к изображению можно указывать с ~

wallpaper {
    monitor = eDP-2
    path = /home/teru/D/Media/Images/Wallpapers/рабочий стол.jpg
    fit_mode = cover # Опционально: cover, contain, tile, fill
}

# Если хотите использовать обои для всех мониторов, оставьте monitor пустым:
# wallpaper {
#     monitor = 
#     path = /path/to/fallback.jpg
# }

splash = false

