# --- АВТОЗАПУСК -----------------------------------------------------

exec-once = LANG=ru_RU.UTF-8 LC_ALL=ru_RU.UTF-8 waybar
#exec-once = waybar                          #   панель задач
exec-once = hyprpaper                       #   обои
#exec-once = prime-run mpvpaper -o "--loop-playlist --hwdec=auto" '*' /home/teru/Program-Files/wallpapers/Miku-x-Shrek.mp4
exec-once = wl-clipboard-history -t         #   ...
exec-once = wl-paste --watch cliphist store #   ...
exec-once = wl-clip-persist --clipboard regular --display wayland-1
exec-once = nm-applet                       #   wi-fi
exec-once = blueman-applet                    #   bluetooth

#exec-once = mpv --no-video --loop-playlist --shuffle ~/Media/Music/Lofi/*

exec-once = [workspace 1]  $terminal        #   терминал
exec-once = [workspace 3]  firefox          #   браузер
exec-once = [workspace 4]  telegram-desktop #   телеграм
#exec-once = [workspace 6]  steam
#exec-once = [workspace 4]  discord          #   дискорд
#exec-once = [workspace 6]  obsidian
#exec-once = [workspace 10] nekoray          #   vpn


