# --- НАСТРОЙКИ МОНИТОРА ---------------------------------------------
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=,2560x1600@165,auto,1.25

env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_RENDERER,vulkan
env = GBM_BACKEND,nvidia-drm
env = __GL_VRR_ALLOWED,1  # Разрешить VRR (если поддерживается)
env = __GL_SYNC_TO_VBLANK,1  # Для уменьшения разрывов изображения
