# Шрифт
font_family Hack

# Размер шрафта
font_size 14.0

# Прозрачность терминала
background_opacity 1

# Отступ по краям
window_padding_width 10

# Цвет фона и текста
background #282a36
foreground #c0caf5

# Цвет выделенного текста
selection_foreground #ffffff
selection_background #6ca1f3

# Оболочка по умолчанию
shell /bin/zsh
